apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-app
  labels:
    app: fiap-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: fiap-app
  template:
    metadata:
      labels:
        app: fiap-app
    spec:
      containers:
      - name: fiap-app
        image: victorsantanna/fiap-app:latest
        ports:
        - containerPort: 6000 
        env:
        - name: ASPNETCORE_URLS
          value: "http://*:6000" 
