apiVersion: v1
kind: Service
metadata:
  name: fiap-app-service
spec:
  selector:
    app: fiap-app
  ports:
    - protocol: TCP
      port: 6000        # Porta externa exposta
      targetPort: 6000  # Porta dentro do container (porta do .NET)
  type: LoadBalancer   # Expor o serviço externamente
