name: Deploy to EKS

on:
  workflow_run:
    workflows:
      - SonarQube Cloud
    types:
      - completed

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest

    steps:
    - name: Download Coverage Artifact
      uses: actions/download-artifact@v3
      with:
        name: coverage
        path: .

    - name: Read Coverage
      id: read-coverage
      run: |
        COVERAGE=$(cat coverage.txt)
        echo "Coverage: $COVERAGE%"
        echo "::set-output name=coverage::$COVERAGE"

    - name: Deploy Application
      if: ${{ steps.read-coverage.outputs.coverage > 70 }}
      run: echo "Deploying application as coverage is greater than 70%"
      
    - name: Deploy Application
      run: echo "Deploying application as coverage is greater than 70%"

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Configure kubectl for EKS
      run: |
        aws eks update-kubeconfig --name fiap-eks--mC1Wnnya --region us-east-1

    - name: Validate Kubernetes Files
      run: |
        ls -R k8s
      working-directory: ./ 

    - name: Apply Kubernetes Service
      run: |
        kubectl apply -f k8s/service.yml
      working-directory: ./

    - name: Apply Kubernetes Deployment
      run: |
        kubectl apply -f k8s/deployment.yml
      working-directory: ./